# Generated by Django 4.2.7 on 2024-06-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicesapp', '0004_alter_ourteam_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='image',
            field=models.ImageField(upload_to='team_member/'),
        ),
    ]
