# Generated by Django 4.2.7 on 2024-06-27 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicesapp', '0005_alter_ourteam_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourteam',
            old_name='instagram',
            new_name='instagram_url',
        ),
    ]
