# Generated by Django 4.2.7 on 2024-06-22 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConstructApp', '0002_alter_setting_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='keyworf',
            new_name='keyword',
        ),
    ]
