# Generated by Django 4.2.7 on 2024-06-22 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConstructApp', '0003_rename_keyworf_setting_keyword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
